language: perl
perl:
  - "5.18"
  - "5.26"
  - "5.28"
env:
  - "HARNESS_OPTIONS=j9 TEST_ONLINE=mongodb://127.0.0.1:27017/minion"
notifications:
  email: false
env:
  matrix:
    - MONGODB=3.4.16
    - MONGODB=3.6.6
    - MONGODB=4.0.0
    - MONGODB=4.1.1
matrix:
  fast_finish: true

install:
  - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-${MONGODB}.tgz
  - tar xzf mongodb-linux-x86_64-${MONGODB}.tgz
  - ${PWD}/mongodb-linux-x86_64-${MONGODB}/bin/mongod --version
  - "cpanm -n --installdeps ."

before_script:
  - mkdir ${PWD}/mongodb-linux-x86_64-${MONGODB}/data
  - ${PWD}/mongodb-linux-x86_64-${MONGODB}/bin/mongod --dbpath ${PWD}/mongodb-linux-x86_64-${MONGODB}/data --logpath ${PWD}/mongodb-linux-x86_64-${MONGODB}/mongodb.log --fork

after_script:
  - pkill mongod
